steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA
      - --cache=true
      - --cache-ttl=720h
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        '$_APP_NAME',
        '--image',
        'gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
      ]
images:
  - gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA

timeout: 1800s

substitutions:
  _APP_NAME: my_app # default value
